/**
 * Generated from backend/app/services/llm/features.py — do not edit by hand.
 * Run `just gen` after changing the table; CI fails when this file is stale.
 */

export type AIFeatureGroup = "talk" | "cast" | "analyse" | "explore" | "prepare" | "system";

export type AIFeatureClass = "reflect" | "analyse" | "option" | "persona" | "draft" | "summarise";

export interface AIFeatureRow {
  id: string;
  label: string;
  group: AIFeatureGroup;
  /** What the model is allowed to hand back (the co-author contract). */
  classification: AIFeatureClass;
  description: string;
  /** What gets sent, in the author's words. */
  context: string[];
  /** num_ctx budget in tokens, capped at call time by the model and the user ceiling. */
  budget: number;
}

export const AI_FEATURE_GROUP_LABELS: Record<AIFeatureGroup, string> = {
  "talk": "Talk",
  "cast": "Ask the cast",
  "analyse": "Analyse",
  "explore": "Explore",
  "prepare": "Prepare",
  "system": "Background",
};

export const AI_FEATURE_CLASS_LABELS: Record<AIFeatureClass, string> = {
  "reflect": "Reflects",
  "analyse": "Analyses",
  "option": "Offers options",
  "persona": "Speaks in character",
  "draft": "Drafts (not manuscript)",
  "summarise": "Summarises",
};

export const AI_FEATURE_CLASS_DESCRIPTIONS: Record<AIFeatureClass, string> = {
  "reflect": "Asks questions and points at your text. Never writes prose for you.",
  "analyse": "Returns structured findings about text you wrote.",
  "option": "Offers short labelled alternatives for you to rewrite in your own words.",
  "persona": "A character answers as themselves, within what they know.",
  "draft": "Drafts non-manuscript material (blurbs, queries, Lorebook fields) for you to edit.",
  "summarise": "Compresses your own text with nothing added.",
};

export const AI_FEATURES: AIFeatureRow[] = [
  {
    id: "scene-chat",
    label: "Scene Assistant",
    group: "talk",
    classification: "reflect",
    description: "Think through the scene you are in: questions, angles, what is missing.",
    context: ["Scene title, synopsis and purpose", "Characters and threads in the scene", "Adjacent scenes"],
    budget: 16384,
  },
  {
    id: "writing-coach",
    label: "Writing Coach",
    group: "talk",
    classification: "reflect",
    description: "Craft feedback on a passage you select — what the prose is doing, not a rewrite.",
    context: ["Selected text", "Scene prose", "Story tone and genre"],
    budget: 16384,
  },
  {
    id: "cliche-coach",
    label: "Cliché Coach",
    group: "talk",
    classification: "reflect",
    description: "Names the tired phrasing in a passage and asks what you meant instead.",
    context: ["Selected text", "Scene prose"],
    budget: 16384,
  },
  {
    id: "identity-workshop",
    label: "Story Identity Workshop",
    group: "talk",
    classification: "reflect",
    description: "A conversation that helps you say what your story is about.",
    context: ["Story identity fields", "Character roles and motivations", "Scene synopses"],
    budget: 32768,
  },
  {
    id: "snowflake-guidance",
    label: "Snowflake Guidance",
    group: "talk",
    classification: "reflect",
    description: "Guidance for the Snowflake Method step you are on.",
    context: ["Current Snowflake step", "Existing outline", "Story premise"],
    budget: 16384,
  },
  {
    id: "interview",
    label: "Character Interview",
    group: "cast",
    classification: "persona",
    description: "Talk to a character as themselves, limited to what they know.",
    context: ["Full character profile", "Relationships", "Arc milestones", "Scenes they were present for"],
    budget: 16384,
  },
  {
    id: "interview-summary",
    label: "Interview Summary",
    group: "cast",
    classification: "summarise",
    description: "Condenses an interview into what was revealed.",
    context: ["Interview transcript"],
    budget: 16384,
  },
  {
    id: "interview-compaction",
    label: "Interview Compaction",
    group: "system",
    classification: "summarise",
    description: "Compresses older interview turns so a long conversation keeps fitting.",
    context: ["Older interview messages"],
    budget: 16384,
  },
  {
    id: "panel-character",
    label: "Panel Interview",
    group: "cast",
    classification: "persona",
    description: "Several characters answer the same question, each in their own voice.",
    context: ["Each character's profile", "Relationships between them", "Panel transcript"],
    budget: 16384,
  },
  {
    id: "panel-orchestrator",
    label: "Panel Turn Order",
    group: "system",
    classification: "analyse",
    description: "Decides which panel members have something to say to a question.",
    context: ["Character names and roles", "Panel transcript"],
    budget: 8192,
  },
  {
    id: "arc-analysis",
    label: "Arc Analysis",
    group: "analyse",
    classification: "analyse",
    description: "How the story arc is tracking against its stated shape.",
    context: ["Story structure", "Scene synopses", "Narrative intent"],
    budget: 32768,
  },
  {
    id: "audience-adherence",
    label: "Audience Fit",
    group: "analyse",
    classification: "analyse",
    description: "Whether the content matches the audience you named.",
    context: ["Scene prose", "Target audience", "Genre and tone"],
    budget: 16384,
  },
  {
    id: "character-arc",
    label: "Character Arc Analysis",
    group: "analyse",
    classification: "analyse",
    description: "Where a character stands in their arc right now.",
    context: ["Character profile and arc notes", "Arc milestones", "Scenes mentioning them"],
    budget: 16384,
  },
  {
    id: "character-dimensionality",
    label: "Character Depth",
    group: "analyse",
    classification: "analyse",
    description: "Contradictions, relationship complexity and flatness across the cast.",
    context: ["Character profiles", "Scene prose", "Relationships", "Thread involvement"],
    budget: 32768,
  },
  {
    id: "character-journey",
    label: "Character Journey",
    group: "analyse",
    classification: "summarise",
    description: "A running account of what a character has been through so far.",
    context: ["Scenes the character appears in", "Arc milestones", "Interview history"],
    budget: 32768,
  },
  {
    id: "cliche-analysis",
    label: "Cliché Check",
    group: "analyse",
    classification: "analyse",
    description: "Overused phrasing, tropes and tired description, with locations.",
    context: ["Scene prose"],
    budget: 16384,
  },
  {
    id: "continuity-check",
    label: "Continuity Check",
    group: "analyse",
    classification: "analyse",
    description: "Timeline, knowledge and detail contradictions between scenes.",
    context: ["Scene prose", "Character profiles", "Story structure"],
    budget: 32768,
  },
  {
    id: "dialogue-attribution",
    label: "Dialogue Attribution",
    group: "analyse",
    classification: "analyse",
    description: "Who is speaking in blocks the deterministic pass could not settle.",
    context: ["Dialogue blocks", "Characters in the scene"],
    budget: 16384,
  },
  {
    id: "discovery",
    label: "Element Extraction",
    group: "analyse",
    classification: "analyse",
    description: "Names in the prose that look like unrecorded characters or places.",
    context: ["Scene prose", "Existing Lorebook entries"],
    budget: 16384,
  },
  {
    id: "discovery-questions",
    label: "Discovery Questions",
    group: "analyse",
    classification: "reflect",
    description: "Questions whose answers would firm up the parts of the story you have not decided.",
    context: ["Story identity", "Character profiles", "Plot threads"],
    budget: 16384,
  },
  {
    id: "economy-analysis",
    label: "Story Economy",
    group: "analyse",
    classification: "analyse",
    description: "Thread balance, scene economy and MICE tightness.",
    context: ["Story structure", "MICE threads", "Scene synopses", "Word counts"],
    budget: 32768,
  },
  {
    id: "editorial-pass",
    label: "Editorial Pass",
    group: "analyse",
    classification: "analyse",
    description: "Fresh-eyes read: priorities, intent gaps, voice notes, marginal comments.",
    context: ["Scene prose", "Stated intent and purpose", "Story identity"],
    budget: 32768,
  },
  {
    id: "essential-questions",
    label: "Story Compass",
    group: "analyse",
    classification: "analyse",
    description: "Whether the six essential story questions can be answered from what exists.",
    context: ["Story intent and premise", "Character goals", "Plot threads", "Structure"],
    budget: 32768,
  },
  {
    id: "extract-outline",
    label: "Outline Extraction",
    group: "analyse",
    classification: "analyse",
    description: "Turns written scenes into a structured outline you can correct.",
    context: ["Scene prose", "Story title and genre"],
    budget: 32768,
  },
  {
    id: "first-pass",
    label: "First-Pass Editor",
    group: "analyse",
    classification: "analyse",
    description: "Reads the prose against the intent and arc milestones you recorded.",
    context: ["Scene prose", "Scene purpose and intent", "Arc milestones", "Narrative goals"],
    budget: 32768,
  },
  {
    id: "image-analysis",
    label: "Image Analysis",
    group: "analyse",
    classification: "analyse",
    description: "Describes what is visible in an image you attached.",
    context: ["The image", "Its caption and attachment context"],
    budget: 8192,
  },
  {
    id: "import-extraction",
    label: "Import Extraction",
    group: "analyse",
    classification: "analyse",
    description: "Pulls character, location and relationship details out of an imported manuscript.",
    context: ["Prose excerpts naming the candidate", "Other candidates in the same scenes"],
    budget: 16384,
  },
  {
    id: "import-structure",
    label: "Import Structure Detection",
    group: "analyse",
    classification: "analyse",
    description: "Proposes the act/chapter/scene split of an imported document.",
    context: ["Imported document headings and paragraphs"],
    budget: 32768,
  },
  {
    id: "outline-alignment",
    label: "Outline Alignment",
    group: "analyse",
    classification: "analyse",
    description: "Where the manuscript has drifted from the outline.",
    context: ["Outline items", "Scene synopses", "Story structure"],
    budget: 32768,
  },
  {
    id: "pacing-analysis",
    label: "Pacing Analysis",
    group: "analyse",
    classification: "analyse",
    description: "Act balance, tension curve and structural rhythm.",
    context: ["Story structure", "Scene synopses", "Word counts", "MICE threads"],
    budget: 32768,
  },
  {
    id: "plot-holes",
    label: "Plot Holes",
    group: "analyse",
    classification: "analyse",
    description: "Logical gaps, dropped questions and inconsistencies.",
    context: ["Scene prose", "Story structure", "Plot threads", "Character motivations"],
    budget: 32768,
  },
  {
    id: "pronoun-identification",
    label: "Pronoun Identification",
    group: "analyse",
    classification: "analyse",
    description: "Finds the pronouns that refer to a character before the deterministic refactor runs.",
    context: ["Scene prose", "Character names and aliases"],
    budget: 16384,
  },
  {
    id: "reader-knowledge-scan",
    label: "Reader Knowledge Scan",
    group: "analyse",
    classification: "analyse",
    description: "Detects reveals, misdirections and clues from scene synopses.",
    context: ["Scene synopses", "Existing knowledge events"],
    budget: 32768,
  },
  {
    id: "session-recap",
    label: "Session Recap",
    group: "analyse",
    classification: "summarise",
    description: "What changed in the story during this working session.",
    context: ["Activity log for the session", "Scene synopses touched"],
    budget: 16384,
  },
  {
    id: "show-dont-tell",
    label: "Show, Don't Tell",
    group: "analyse",
    classification: "analyse",
    description: "Points at passages that state what could be shown, and names the telling.",
    context: ["Scene prose", "Genre and tone"],
    budget: 16384,
  },
  {
    id: "story-summary",
    label: "Story Summary",
    group: "analyse",
    classification: "summarise",
    description: "A summary of everything written so far, with nothing added.",
    context: ["All scene prose", "Story title and narrative intent"],
    budget: 32768,
  },
  {
    id: "structure-summary",
    label: "Section Summary",
    group: "analyse",
    classification: "summarise",
    description: "Summarises one act, chapter or section on its own terms.",
    context: ["Prose within the section", "Section purpose"],
    budget: 32768,
  },
  {
    id: "system-analysis",
    label: "World System Analysis",
    group: "analyse",
    classification: "analyse",
    description: "Edge cases and story consequences of a world system's rules.",
    context: ["System rules", "Other world systems", "Cultures that use it"],
    budget: 8192,
  },
  {
    id: "theme-tracker",
    label: "Theme Tracker",
    group: "analyse",
    classification: "analyse",
    description: "Recurring themes and motifs, and where they develop.",
    context: ["Scene prose", "Story intent", "Plot threads"],
    budget: 32768,
  },
  {
    id: "thread-analysis",
    label: "Thread Analysis",
    group: "analyse",
    classification: "analyse",
    description: "How a plot thread progresses, and where it goes quiet.",
    context: ["Thread description", "Scenes tagged to the thread", "Thread status"],
    budget: 32768,
  },
  {
    id: "travel-analysis",
    label: "Travel Route Analysis",
    group: "analyse",
    classification: "analyse",
    description: "Hazards, tensions and story potential along a route.",
    context: ["Origin and destination", "World systems on the route", "Cultures along the way"],
    budget: 8192,
  },
  {
    id: "twist-analysis",
    label: "Twist Analysis",
    group: "analyse",
    classification: "analyse",
    description: "Clue quality, distribution and whether the reveal lands.",
    context: ["Twist description", "Linked clues", "Scenes mentioning it"],
    budget: 16384,
  },
  {
    id: "twist-impact",
    label: "Twist Impact",
    group: "analyse",
    classification: "analyse",
    description: "What changes downstream once a twist resolves.",
    context: ["Twist description", "Plot threads", "Character arcs", "Scene synopses"],
    budget: 16384,
  },
  {
    id: "voice-fidelity",
    label: "Voice Fidelity",
    group: "analyse",
    classification: "analyse",
    description: "Whether a character's dialogue stays in their own voice.",
    context: ["The character's dialogue lines", "Their voice notes"],
    budget: 16384,
  },
  {
    id: "brainstorm",
    label: "What's Next?",
    group: "explore",
    classification: "option",
    description: "Short labelled directions the scene could take.",
    context: ["Scene synopsis and purpose", "Plot threads", "Character arcs", "Adjacent scenes"],
    budget: 16384,
  },
  {
    id: "whatif",
    label: "What-If",
    group: "explore",
    classification: "option",
    description: "Consequences of an alternate choice — never the alternate scene.",
    context: ["Story structure", "Plot threads", "Character motivations", "Lorebook"],
    budget: 32768,
  },
  {
    id: "scene-plan",
    label: "Scene Planner",
    group: "explore",
    classification: "option",
    description: "Questions and a few one-line beat options for a scene you are about to write.",
    context: ["Scene title, synopsis and purpose", "Adjacent scenes", "Characters", "Active threads"],
    budget: 16384,
  },
  {
    id: "scene-atmosphere",
    label: "Scene Atmosphere Cues",
    group: "explore",
    classification: "option",
    description: "Short sensory cues per sense to write from — not description to paste.",
    context: ["Scene setting and purpose", "Story tone"],
    budget: 8192,
  },
  {
    id: "what-exists",
    label: "What Exists Here",
    group: "explore",
    classification: "option",
    description: "What would plausibly exist at a location, given the world you built.",
    context: ["Location details", "World systems", "Connected cultures"],
    budget: 8192,
  },
  {
    id: "element-suggest",
    label: "World Element Suggestions",
    group: "explore",
    classification: "option",
    description: "Naming, ritual and detail directions for a world element.",
    context: ["The element's own fields", "Associated systems", "Related cultures and eras"],
    budget: 8192,
  },
  {
    id: "historical-implications",
    label: "Historical Implications",
    group: "explore",
    classification: "option",
    description: "Present-day ripples of a historical event.",
    context: ["Event details", "Era context", "Cultures and systems affected"],
    budget: 8192,
  },
  {
    id: "calendar-suggestions",
    label: "Calendar Suggestions",
    group: "explore",
    classification: "option",
    description: "Festivals, seasons and observed days for a calendar.",
    context: ["Calendar structure", "Associated cultures", "Historical events"],
    budget: 8192,
  },
  {
    id: "character-attributes",
    label: "Attribute Suggestions",
    group: "prepare",
    classification: "draft",
    description: "Short suggestions for one Lorebook field, for you to pick from or edit.",
    context: ["Character name, role and personality", "Existing traits", "Story context"],
    budget: 8192,
  },
  {
    id: "character-from-image",
    label: "Character from Image",
    group: "prepare",
    classification: "draft",
    description: "What is visible in a reference image, plus attributes marked as suggestions.",
    context: ["The image", "Existing character fields"],
    budget: 8192,
  },
  {
    id: "codex-suggest",
    label: "Codex Suggestions",
    group: "prepare",
    classification: "analyse",
    description: "Reads a scene and proposes who was in it and what it establishes, each quoting the line it read that from. Nothing counts until you confirm it.",
    context: ["The scene's prose", "The cast, and who the graph already places in the scene", "Facts already recorded"],
    budget: 16384,
  },
  {
    id: "relationship-suggest",
    label: "Relationship Suggestions",
    group: "prepare",
    classification: "option",
    description: "Dynamics worth recording between characters, confirmed before anything is created.",
    context: ["Character profiles", "Existing relationships"],
    budget: 16384,
  },
  {
    id: "book-description",
    label: "Book Description",
    group: "prepare",
    classification: "draft",
    description: "Back-cover copy to rewrite in your own voice.",
    context: ["Story identity", "Main characters", "Central conflict", "Themes"],
    budget: 16384,
  },
  {
    id: "query-letter",
    label: "Query Letter",
    group: "prepare",
    classification: "draft",
    description: "A query draft to rewrite — agents can tell when a letter was not written by the author.",
    context: ["Story identity and word count", "Main characters and conflict", "Comp titles"],
    budget: 16384,
  },
  {
    id: "comp-titles",
    label: "Comparable Titles",
    group: "prepare",
    classification: "option",
    description: "Published books your story sits beside, with why.",
    context: ["Genre, audience and tone", "Logline and premise", "Themes"],
    budget: 8192,
  },
  {
    id: "conversation-summarize",
    label: "Conversation Summary",
    group: "system",
    classification: "summarise",
    description: "Compresses a long AI conversation so it keeps fitting in context.",
    context: ["The conversation so far"],
    budget: 16384,
  },
  {
    id: "session-title-generation",
    label: "Session Title",
    group: "system",
    classification: "summarise",
    description: "Names an AI session from its first exchange.",
    context: ["First messages of the session"],
    budget: 8192,
  },
  {
    id: "scene-summary-batch",
    label: "Scene Summaries",
    group: "system",
    classification: "summarise",
    description: "Refreshes scene synopses in bulk so context assembly has something to use.",
    context: ["Scene prose"],
    budget: 16384,
  },
];

export const AI_FEATURES_BY_ID: Record<string, AIFeatureRow> = Object.fromEntries(
  AI_FEATURES.map((f) => [f.id, f]),
);

/** Label for a feature id; unknown ids are title-cased so nothing renders raw. */
export function aiFeatureLabel(id: string): string {
  const feature = AI_FEATURES_BY_ID[id];
  if (feature) return feature.label;
  return id.replace(/[-_]/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
}
