"""baseline

Revision ID: 0001_baseline
Revises: 
Create Date: 2026-09-05 17:14:46.733675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_baseline'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('beat_sheets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('beats', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('intent', sa.Text(), nullable=False),
    sa.Column('structure_template_id', sa.String(), nullable=False),
    sa.Column('genre', sa.String(), nullable=False),
    sa.Column('tone', sa.String(), nullable=False),
    sa.Column('themes', sa.JSON(), nullable=False),
    sa.Column('central_conflict', sa.Text(), nullable=False),
    sa.Column('target_audience', sa.String(), nullable=False),
    sa.Column('intended_length', sa.String(), nullable=False),
    sa.Column('beat_sheet_id', sa.String(), nullable=True),
    sa.Column('narrative_intent', sa.Text(), nullable=False),
    sa.Column('premise', sa.Text(), nullable=False),
    sa.Column('logline', sa.String(), nullable=False),
    sa.Column('narrative_perspective', sa.String(), nullable=False),
    sa.Column('pov_character_id', sa.String(), nullable=True),
    sa.Column('snowflake_sentence', sa.Text(), nullable=False),
    sa.Column('snowflake_paragraph', sa.Text(), nullable=False),
    sa.Column('snowflake_synopsis', sa.Text(), nullable=False),
    sa.Column('goals', sa.JSON(), nullable=False),
    sa.Column('discovery_enabled', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('discovery_auto_analyze', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('discovery_element_types', sa.JSON(), nullable=False),
    sa.Column('discovery_min_confidence', sa.Float(), server_default='0.6', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pov_character_id'], ['characters.id'], name='fk_stories_pov_character_id', use_alter=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('story_structure_templates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('levels', sa.JSON(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_backup_defaults',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('auto_enabled', sa.Boolean(), nullable=False),
    sa.Column('interval_minutes', sa.Integer(), nullable=False),
    sa.Column('max_count', sa.Integer(), nullable=True),
    sa.Column('max_age_days', sa.Integer(), nullable=True),
    sa.Column('include_diagrams', sa.Boolean(), nullable=False),
    sa.Column('include_interviews', sa.Boolean(), nullable=False),
    sa.Column('include_chat_sessions', sa.Boolean(), nullable=False),
    sa.Column('include_activity_logs', sa.Boolean(), nullable=False),
    sa.Column('activity_log_limit', sa.Integer(), nullable=True),
    sa.Column('include_media_assets', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('activity_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('story_id', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('starred', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_logs_story_id'), ['story_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_logs_user_id'), ['user_id'], unique=False)

    op.create_table('calendars',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('story_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('months', sa.JSON(), nullable=False),
    sa.Column('days_per_week', sa.Integer(), nullable=False),
    sa.Column('week_day_names', sa.JSON(), nullable=False),
    sa.Column('special_days', sa.JSON(), nullable=False),
    sa.Column('epoch_name', sa.String(), nullable=False),
    sa.Column('conversion_notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('characters',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('story_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('character_type', sa.String(), nullable=False),
    sa.Column('jungian_archetype', sa.String(), nullable=False),
    sa.Column('narrative_archetype', sa.String(), nullable=False),
    sa.Column('personality', sa.Text(), nullable=False),
    sa.Column('motivation', sa.Text(), nullable=False),
    sa.Column('background', sa.Text(), nullable=False),
    sa.Column('appearance', sa.Text(), nullable=False),
    sa.Column('arc_notes', sa.Text(), nullable=False),
    sa.Column('interview_prompts', sa.JSON(), nullable=False),
    sa.Column('traits', sa.JSON(), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('mission_statement', sa.Text(), nullable=False),
    sa.Column('narrative_intent', sa.Text(), nullable=False),
    sa.Column('narrative_intent_hidden', sa.Boolean(), nullable=False),
    sa.Column('pronouns', sa.String(), nullable=False),
    sa.Column('arc_milestones', sa.JSON(), nullable=False),
    sa.Column('discovery_notes', sa.JSON(), nullable=False),
    sa.Column('snowflake_summary', sa.Text(), nullable=False),
    sa.Column('snowflake_synopsis', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_characters_story_id'), ['story_id'], unique=False)

    op.create_table('chat_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('story_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('context_type', sa.String(), nullable=False),
    sa.Column('context_id', sa.String(), nullable=True),
    sa.Column('context_label', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_sessions_story_id'), ['story_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('cultures',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('story_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('values', sa.Text(), nullable=False),
    sa.Column('customs', sa.Text(), nullable=False),
    sa.Column('taboos', sa.Text(), nullable=False),
    sa.Column('religion', sa.Text(), nullable=False),
    sa.Column('government_type', sa.String(), nullable=False),
    sa.Column('economy', sa.Text(), nullable=False),
    sa.Column('social_hierarchy', sa.Text(), nullable=False),
    sa.Column('naming_conventions', sa.JSON(), nullable=False),
    sa.Column('common_phrases', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eras',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('story_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('start_date', sa.String(), nullable=False),
    sa.Column('end_date', sa.String(), nullable=False),
    sa.Column('characteristics', sa.Text(), nullable=False),
    sa.Column('key_figures', sa.JSON(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outlines',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('story_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('source_beat_sheet_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('panel_interviews',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('story_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('character_ids', sa.JSON(), nullable=False),
    sa.Column('messages', sa.JSON(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plot_threads',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('story_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('mice_type', sa.String(), nullable=True),
    sa.Column('opens_at_node_id', sa.String(), nullable=True),
    sa.Column('closes_at_node_id', sa.String(), nullable=True),
    sa.Column('try_fail_cycles', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plot_threads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plot_threads_story_id'), ['story_id'], unique=False)

    op.create_table('settings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('story_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('atmosphere', sa.Text(), nullable=False),
    sa.Column('history', sa.Text(), nullable=False),
    sa.Column('significance', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('story_assets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('story_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('stored_path', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('alt_text', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('story_backup_settings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('story_id', sa.String(), nullable=False),
    sa.Column('auto_enabled', sa.Boolean(), nullable=False),
    sa.Column('interval_minutes', sa.Integer(), nullable=False),
    sa.Column('max_count', sa.Integer(), nullable=True),
    sa.Column('max_age_days', sa.Integer(), nullable=True),
    sa.Column('last_auto_backup_at', sa.DateTime(), nullable=True),
    sa.Column('include_diagrams', sa.Boolean(), nullable=False),
    sa.Column('include_interviews', sa.Boolean(), nullable=False),
    sa.Column('include_chat_sessions', sa.Boolean(), nullable=False),
    sa.Column('include_activity_logs', sa.Boolean(), nullable=False),
    sa.Column('activity_log_limit', sa.Integer(), nullable=True),
    sa.Column('include_media_assets', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('story_id')
    )
    op.create_table('story_notes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('story_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('story_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('story_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('trigger', sa.String(), nullable=False),
    sa.Column('snapshot_type', sa.String(), nullable=False),
    sa.Column('base_snapshot_id', sa.String(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('delta_summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['base_snapshot_id'], ['story_snapshots.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('world_systems',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('story_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('system_type', sa.String(), nullable=False),
    sa.Column('source_origin', sa.Text(), nullable=False),
    sa.Column('rules', sa.Text(), nullable=False),
    sa.Column('limitations', sa.Text(), nullable=False),
    sa.Column('costs', sa.Text(), nullable=False),
    sa.Column('hierarchy_tiers', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asset_attachments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('object_type', sa.String(), nullable=False),
    sa.Column('object_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['story_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character_relationships',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('character_id', sa.String(), nullable=False),
    sa.Column('related_character_id', sa.String(), nullable=False),
    sa.Column('relationship_type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('strength', sa.JSON(), nullable=False),
    sa.Column('visibility', sa.String(), nullable=False),
    sa.Column('narrative_purpose', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('is_suggested', sa.Boolean(), nullable=False),
    sa.Column('suggestion_source', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['related_character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id', 'related_character_id', name='uq_relationship_directed_pair')
    )
    with op.batch_alter_table('character_relationships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_character_relationships_character_id'), ['character_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_character_relationships_related_character_id'), ['related_character_id'], unique=False)

    op.create_table('chat_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_session_id'), ['session_id'], unique=False)

    op.create_table('compendium_entries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('story_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('entry_type', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('url_title', sa.String(), nullable=True),
    sa.Column('url_description', sa.Text(), nullable=True),
    sa.Column('url_fetched_at', sa.DateTime(), nullable=True),
    sa.Column('asset_id', sa.String(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['story_assets.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historical_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('story_id', sa.String(), nullable=False),
    sa.Column('era_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('in_world_date', sa.String(), nullable=False),
    sa.Column('participants', sa.JSON(), nullable=False),
    sa.Column('causes', sa.Text(), nullable=False),
    sa.Column('consequences', sa.Text(), nullable=False),
    sa.Column('legacy_effects', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['era_id'], ['eras.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outline_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('outline_id', sa.String(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('beat_type', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('collapsed', sa.Boolean(), nullable=False),
    sa.Column('scene_id', sa.String(), nullable=True),
    sa.Column('scene_title', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['outline_id'], ['outlines.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['outline_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('structure_nodes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('story_id', sa.String(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('level_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('synopsis', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('entry_state', sa.Text(), nullable=False),
    sa.Column('exit_state', sa.Text(), nullable=False),
    sa.Column('key_events', sa.Text(), nullable=False),
    sa.Column('timeline_position', sa.Integer(), nullable=True),
    sa.Column('content_summary', sa.Text(), server_default='', nullable=False),
    sa.Column('summary_stale', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('summary_updated_at', sa.DateTime(), nullable=True),
    sa.Column('beat_id', sa.String(), nullable=True),
    sa.Column('pov_character_id', sa.String(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['structure_nodes.id'], ),
    sa.ForeignKeyConstraint(['pov_character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('structure_nodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_structure_nodes_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_structure_nodes_story_id'), ['story_id'], unique=False)

    op.create_table('character_interviews',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('character_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('context_node_id', sa.String(), nullable=True),
    sa.Column('messages', sa.JSON(), nullable=False),
    sa.Column('interview_notes', sa.Text(), nullable=False),
    sa.Column('compacted_summary', sa.Text(), nullable=True),
    sa.Column('compaction_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['context_node_id'], ['structure_nodes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('character_interviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_character_interviews_character_id'), ['character_id'], unique=False)

    op.create_table('character_journey_summaries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('character_id', sa.String(), nullable=False),
    sa.Column('up_to_node_id', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('source_node_ids', sa.Text(), server_default='', nullable=False),
    sa.Column('is_stale', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['up_to_node_id'], ['structure_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('character_journey_summaries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_character_journey_summaries_character_id'), ['character_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_character_journey_summaries_up_to_node_id'), ['up_to_node_id'], unique=False)

    op.create_table('compendium_attachments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('entry_id', sa.String(), nullable=False),
    sa.Column('object_type', sa.String(), nullable=False),
    sa.Column('object_id', sa.String(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['compendium_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diagrams',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('story_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('diagram_type', sa.String(), nullable=False),
    sa.Column('nodes', sa.JSON(), nullable=False),
    sa.Column('edges', sa.JSON(), nullable=False),
    sa.Column('attached_node_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['attached_node_id'], ['structure_nodes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dialogue_blocks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('scene_id', sa.String(), nullable=False),
    sa.Column('character_id', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('paragraph_index', sa.Integer(), nullable=False),
    sa.Column('position_in_paragraph', sa.Integer(), nullable=False),
    sa.Column('attribution_method', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('speaker_name', sa.String(), nullable=False),
    sa.Column('dialogue_type', sa.String(), nullable=True),
    sa.Column('subtext', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['scene_id'], ['structure_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dialogue_blocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dialogue_blocks_character_id'), ['character_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dialogue_blocks_scene_id'), ['scene_id'], unique=False)

    op.create_table('discovered_elements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('story_id', sa.String(), nullable=False),
    sa.Column('element_type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source_node_id', sa.String(), nullable=True),
    sa.Column('source_excerpt', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), server_default='pending', nullable=False),
    sa.Column('merged_to_type', sa.String(), nullable=True),
    sa.Column('merged_to_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_node_id'], ['structure_nodes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plot_thread_appearances',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('thread_id', sa.String(), nullable=False),
    sa.Column('node_id', sa.String(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['structure_nodes.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['plot_threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plot_thread_appearances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plot_thread_appearances_node_id'), ['node_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plot_thread_appearances_thread_id'), ['thread_id'], unique=False)

    op.create_table('scene_links',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('story_id', sa.String(), nullable=False),
    sa.Column('source_node_id', sa.String(), nullable=False),
    sa.Column('target_node_id', sa.String(), nullable=False),
    sa.Column('link_type', sa.String(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_node_id'], ['structure_nodes.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.ForeignKeyConstraint(['target_node_id'], ['structure_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('story_todos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('story_id', sa.String(), nullable=False),
    sa.Column('node_id', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('doc_from', sa.Integer(), nullable=True),
    sa.Column('doc_to', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['structure_nodes.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('story_todos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_story_todos_node_id'), ['node_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_story_todos_story_id'), ['story_id'], unique=False)

    op.create_table('twists',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('story_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('the_truth', sa.Text(), nullable=False),
    sa.Column('the_misdirection', sa.Text(), nullable=False),
    sa.Column('twist_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('revealed_at_node_id', sa.String(), nullable=True),
    sa.Column('clues', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['revealed_at_node_id'], ['structure_nodes.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('story_id', sa.String(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location_type', sa.String(), nullable=False),
    sa.Column('climate', sa.String(), nullable=False),
    sa.Column('terrain', sa.Text(), nullable=False),
    sa.Column('political_affiliation', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('atmosphere', sa.Text(), nullable=False),
    sa.Column('history', sa.Text(), nullable=False),
    sa.Column('significance', sa.Text(), nullable=False),
    sa.Column('orbital_period', sa.String(), nullable=False),
    sa.Column('distance_from_parent', sa.String(), nullable=False),
    sa.Column('gravity', sa.String(), nullable=False),
    sa.Column('habitability', sa.String(), nullable=False),
    sa.Column('radiation_level', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_stub', sa.Boolean(), nullable=False),
    sa.Column('discovered_from_id', sa.String(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['discovered_from_id'], ['discovered_elements.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reader_knowledge_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('story_id', sa.String(), nullable=False),
    sa.Column('node_id', sa.String(), nullable=True),
    sa.Column('twist_id', sa.String(), nullable=True),
    sa.Column('knowledge_type', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('reader_knows', sa.Boolean(), nullable=False),
    sa.Column('characters_who_know', sa.JSON(), nullable=True),
    sa.Column('is_truth', sa.Boolean(), nullable=False),
    sa.Column('supersedes_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['structure_nodes.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.ForeignKeyConstraint(['twist_id'], ['twists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location_travel',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('from_location_id', sa.String(), nullable=False),
    sa.Column('to_location_id', sa.String(), nullable=False),
    sa.Column('travel_time', sa.String(), nullable=False),
    sa.Column('travel_method', sa.String(), nullable=False),
    sa.Column('condition', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('bidirectional', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['from_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['to_location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scene_settings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('location_id', sa.String(), nullable=False),
    sa.Column('node_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['node_id'], ['structure_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scene_settings')
    op.drop_table('location_travel')
    op.drop_table('reader_knowledge_events')
    op.drop_table('locations')
    op.drop_table('twists')
    with op.batch_alter_table('story_todos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_story_todos_story_id'))
        batch_op.drop_index(batch_op.f('ix_story_todos_node_id'))

    op.drop_table('story_todos')
    op.drop_table('scene_links')
    with op.batch_alter_table('plot_thread_appearances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plot_thread_appearances_thread_id'))
        batch_op.drop_index(batch_op.f('ix_plot_thread_appearances_node_id'))

    op.drop_table('plot_thread_appearances')
    op.drop_table('discovered_elements')
    with op.batch_alter_table('dialogue_blocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dialogue_blocks_scene_id'))
        batch_op.drop_index(batch_op.f('ix_dialogue_blocks_character_id'))

    op.drop_table('dialogue_blocks')
    op.drop_table('diagrams')
    op.drop_table('compendium_attachments')
    with op.batch_alter_table('character_journey_summaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_character_journey_summaries_up_to_node_id'))
        batch_op.drop_index(batch_op.f('ix_character_journey_summaries_character_id'))

    op.drop_table('character_journey_summaries')
    with op.batch_alter_table('character_interviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_character_interviews_character_id'))

    op.drop_table('character_interviews')
    with op.batch_alter_table('structure_nodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_structure_nodes_story_id'))
        batch_op.drop_index(batch_op.f('ix_structure_nodes_parent_id'))

    op.drop_table('structure_nodes')
    op.drop_table('outline_items')
    op.drop_table('historical_events')
    op.drop_table('compendium_entries')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_session_id'))

    op.drop_table('chat_messages')
    with op.batch_alter_table('character_relationships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_character_relationships_related_character_id'))
        batch_op.drop_index(batch_op.f('ix_character_relationships_character_id'))

    op.drop_table('character_relationships')
    op.drop_table('asset_attachments')
    op.drop_table('world_systems')
    op.drop_table('story_snapshots')
    op.drop_table('story_notes')
    op.drop_table('story_backup_settings')
    op.drop_table('story_assets')
    op.drop_table('settings')
    with op.batch_alter_table('plot_threads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plot_threads_story_id'))

    op.drop_table('plot_threads')
    op.drop_table('panel_interviews')
    op.drop_table('outlines')
    op.drop_table('eras')
    op.drop_table('cultures')
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_chat_sessions_story_id'))

    op.drop_table('chat_sessions')
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_characters_story_id'))

    op.drop_table('characters')
    op.drop_table('calendars')
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_activity_logs_story_id'))

    op.drop_table('activity_logs')
    op.drop_table('user_backup_defaults')
    op.drop_table('story_structure_templates')
    op.drop_table('stories')
    op.drop_table('beat_sheets')
    op.drop_table('users')
    # ### end Alembic commands ###
