"""add summary_updated_at to structure_nodes

Revision ID: 834a36e69b30
Revises: 2060897ed49f
Create Date: 2026-04-14 08:04:23.714364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '834a36e69b30'
down_revision: Union[str, None] = '2060897ed49f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('structure_nodes', sa.Column('summary_updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('structure_nodes', 'summary_updated_at')
    # ### end Alembic commands ###
