"""add_indexes_to_fk_columns

Revision ID: 92c0ea8ef898
Revises: 032_reader_knowledge_events
Create Date: 2026-04-13 09:05:58.200694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92c0ea8ef898'
down_revision: Union[str, None] = '032_reader_knowledge_events'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_activity_logs_story_id'), 'activity_logs', ['story_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_user_id'), 'activity_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_character_interviews_character_id'), 'character_interviews', ['character_id'], unique=False)
    op.create_index(op.f('ix_character_journey_summaries_character_id'), 'character_journey_summaries', ['character_id'], unique=False)
    op.create_index(op.f('ix_character_journey_summaries_up_to_node_id'), 'character_journey_summaries', ['up_to_node_id'], unique=False)
    op.create_index(op.f('ix_character_relationships_character_id'), 'character_relationships', ['character_id'], unique=False)
    op.create_index(op.f('ix_character_relationships_related_character_id'), 'character_relationships', ['related_character_id'], unique=False)
    op.create_index(op.f('ix_characters_story_id'), 'characters', ['story_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_story_id'), 'chat_sessions', ['story_id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_dialogue_blocks_character_id'), 'dialogue_blocks', ['character_id'], unique=False)
    op.create_index(op.f('ix_dialogue_blocks_scene_id'), 'dialogue_blocks', ['scene_id'], unique=False)
    op.create_index(op.f('ix_plot_thread_appearances_node_id'), 'plot_thread_appearances', ['node_id'], unique=False)
    op.create_index(op.f('ix_plot_thread_appearances_thread_id'), 'plot_thread_appearances', ['thread_id'], unique=False)
    op.create_index(op.f('ix_plot_threads_story_id'), 'plot_threads', ['story_id'], unique=False)
    op.create_index(op.f('ix_structure_nodes_parent_id'), 'structure_nodes', ['parent_id'], unique=False)
    op.create_index(op.f('ix_structure_nodes_story_id'), 'structure_nodes', ['story_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_structure_nodes_story_id'), table_name='structure_nodes')
    op.drop_index(op.f('ix_structure_nodes_parent_id'), table_name='structure_nodes')
    op.drop_index(op.f('ix_plot_threads_story_id'), table_name='plot_threads')
    op.drop_index(op.f('ix_plot_thread_appearances_thread_id'), table_name='plot_thread_appearances')
    op.drop_index(op.f('ix_plot_thread_appearances_node_id'), table_name='plot_thread_appearances')
    op.drop_index(op.f('ix_dialogue_blocks_scene_id'), table_name='dialogue_blocks')
    op.drop_index(op.f('ix_dialogue_blocks_character_id'), table_name='dialogue_blocks')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_story_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_characters_story_id'), table_name='characters')
    op.drop_index(op.f('ix_character_relationships_related_character_id'), table_name='character_relationships')
    op.drop_index(op.f('ix_character_relationships_character_id'), table_name='character_relationships')
    op.drop_index(op.f('ix_character_journey_summaries_up_to_node_id'), table_name='character_journey_summaries')
    op.drop_index(op.f('ix_character_journey_summaries_character_id'), table_name='character_journey_summaries')
    op.drop_index(op.f('ix_character_interviews_character_id'), table_name='character_interviews')
    op.drop_index(op.f('ix_activity_logs_user_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_story_id'), table_name='activity_logs')
    # ### end Alembic commands ###
